print = input('Oie, Boa Tarde!')
print = input('Tudo bem? ')
print = input('Que bom, Eu também estou bem, obrigado!')
print = input('Qual é o seu nome? ')
print = input('Que bom, o meu nome é Rex')
print = input('Quantos anos você tem? ')
print = input('Eu tenho 25 anos')
